# Generated by Django 4.2.7 on 2023-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leave_a_message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=256, verbose_name="用户名")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
            ],
            options={
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
                "db_table": "leave_a_message",
            },
        ),
    ]
