# Generated by Django 4.2.7 on 2023-12-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="标题")),
                ("picture", models.CharField(max_length=256, verbose_name="图片")),
                ("district", models.CharField(max_length=20, verbose_name="区域")),
                ("address", models.CharField(max_length=20, verbose_name="地址")),
                ("area", models.CharField(max_length=20, verbose_name="面积(㎡)")),
                ("direction", models.CharField(max_length=20, verbose_name="朝向")),
                ("types", models.CharField(max_length=20, verbose_name="类型")),
                ("floor", models.CharField(max_length=50, verbose_name="楼层")),
                ("price", models.FloatField(verbose_name="租金(元/月)")),
                ("remark", models.CharField(max_length=150, verbose_name="备注")),
                ("link", models.CharField(max_length=256, verbose_name="详细信息")),
                (
                    "add_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
                ("mod_date", models.DateTimeField(auto_now=True, verbose_name="修改日期")),
            ],
            options={
                "verbose_name": "租房",
                "verbose_name_plural": "租房",
                "db_table": "rent_house",
            },
        ),
    ]
